### ISSUE TITLE
Problem with refunds: UnrecognizedPropertyException: Unrecognized field "AuthorisationID"

### ISSUE THREAD

**Issue by davidwebster48** [eWAYPayment/eway-rapid-java#2]
When trying to process a refund I get an error. Please find my log attached.
[refund_error_log.txt](https://github.com/eWAYPayment/eway-rapid-java/files/121021/refund_error_log.txt)

**Comment by incarnate** [comment]
Thanks for the raising the issue and the attached log David. 
Some extra fields were added to the Refund response at the end of last year and the eWAY Java SDK can't handle new fields, which is clearly a problem.

I've got a fix almost ready so that unknown fields will be ignored, it should be released tomorrow morning (version 1.1.1).

**Comment by incarnate** [comment]
eWAY Java SDK v1.1.1 is now up on Maven Central, it will ignore any fields that Rapid sends that aren't mapped.

Thanks again for the bug report David!
